# Generated by Django 4.1.3 on 2023-03-17 10:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ShortURL",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_url", models.URLField(max_length=250)),
                ("short_url", models.CharField(max_length=8, unique=True)),
                ("premium", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("access_count", models.IntegerField(default=0)),
            ],
        ),
    ]
