# Generated by Django 4.1.3 on 2023-03-17 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shorter_url", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="shorturl", old_name="access_count", new_name="times_clicked",
        ),
    ]
